blank_issues_enabled: true
contact_links:
  - name: "⚠️ Report Archive Today Service Issues"
    url: "https://archive.today/"
    about: |
      This extension is NOT affiliated with Archive Today.
      Issues with that service should be reported through the Archive Today website (email).
