name: TruffleHog One-Shot Scan

on:
  workflow_dispatch:  # Allows you to trigger the scan manually

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run TruffleHog
        uses: nasa-gibs/trufflehog-actions-scan@v3
